import { GetServerSideProps } from "next";
import { getDogs, queryClient } from "../src/api";
import { dehydrate, useQuery } from "@tanstack/react-query";
import Head from "next/head";
import Header from "../components/Header";
import CardDog from "../components/CardDog";
import Link from "next/link";
import { useToggleState } from "../context/StateProvider";

export const getServerSideProps: GetServerSideProps = async ({}) => {
  await queryClient.prefetchQuery(["dogs"], () => getDogs());
  return {
    props: {
      dehydratedData: dehydrate(queryClient),
    },
  };
};

export default function Home() {
  const { data, isLoading, isFetching } = useQuery(["dogs"], () => getDogs());
  const [isOpen] = useToggleState();
  return (
    <>
      <Head>
        <title>Next.js + Geaph QL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div
        className={`grid grid-cols-1 md:grid-cols-2 py-10 ${
          !isOpen && "place-items-center"
        } lg:grid-cols-3 max-w-5xl mx-auto gap-2 `}>
        {isFetching || isLoading ? (
          [...new Array(10).fill(0)].map((_, key) => (
            <CardDog key={key} isLoading={isLoading || isFetching} />
          ))
        ) : (
          <>
            {data?.dogs.map((dog, index) => (
              <Link href={`/dog/${dog.name}`} passHref key={index}>
                <CardDog dog={dog} />
              </Link>
            ))}
          </>
        )}
      </div>
    </>
  );
}
